### PR TITLE
Support PHP 8

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Adds support for PHP 7.4 and 8.0.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks for your work on this. It seems like the tests are still failing, could you take a look at that?

**Comment by GrahamCampbell** [comment]
The prefer-lowest config should go. All it does it highlight issues with phpunit's own version constraints for its dependencies.

**Comment by GrahamCampbell** [comment]
Passing now. :)

**Comment by freekmurze** [comment]
Thanks! Much appreciated!

**Pull request merged**
