### PR TITLE
use the dropbox provided content hash for flysystem checksum

### PR DESCRIPTION
**Pull request by Gummibeer**
closes #91

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

It seems the tests are failing. Could you take a look at that?

**Comment by Gummibeer** [comment]
It's the lowest tests failing as the `ChecksumProvider` interface was added in v3.7 but the package supports `thephpleague/flysystem: "^2.0.4 || ^3.0.0",` - should the minimum version be bumped? Unsure how else we could fix the problem?
And two tests have a warning.

**Comment by Gummibeer** [comment]
@freekmurze done and also fixed the deprecation warning. I assume that this would lead to a new major version of the package? 🤔
As it's BC in several ways.

**Comment by freekmurze** [comment]
Thanks, I'll tag a new major version indeed.

**Pull request merged**
